name: map
description: Map widget for Flutter written in 100% Dart. Supports Android, iOS, Web and Desktop.
version: 1.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/flutter_map

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlng: ^0.1.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
